### ISSUE TITLE
I can't find the generated file, why?

### ISSUE THREAD

**Issue by mangopulp1** [FatyCaty/WebsiteCreatorToolV2#1]
I can't find the generated file, why?

**Comment by FatyCaty** [comment]
While testing I cant seem to fine this issue? Try downloading the new exe I compiled!

**Comment by FatyCaty** [comment]
Hello @mangopulp1 
I have found another issue that might be related to the issue you have. I have now once again compiled
a new exe with a jdk so now the program actually runs 😆.
Make sure to keep the jdk in the same directory and that should fix your issue.

**Comment by mangopulp1** [comment]
thanks a lot
